### ISSUE TITLE
"error: no such module" in playground after running Arena

### ISSUE THREAD

**Issue by pjamroz** [finestructure/Arena#18]
After running: `$ arena https://github.com/davedelong/time -p ios`
MyPlayground has one line:

`import Time`

running the playground ends with:

```
error: MyPlayground.playground:1:8: error: no such module 'Time'
import Time
```

same happens with other SPM libs I tried. Also with local lib.

Xcode 11.3.1, Arena 0.8.1, Catalina 10.15.3

**Comment by finestructure** [comment]
I see you’ve closed the ticket - was the issue that you hadn’t built the project?

Please let me know, I’m thinking about adding a comment above the import statement to remind users.

**Comment by finestructure** [comment]
I've added a comment to the top of the file to help with this issue (I keep getting this myself).

**Comment by pjamroz** [comment]
Yes after making some tests, I've closed the ticket. First thing is to build the newly created project before running the playground. That was something I missed when I wrote this issue in first place.
However then I stumbled upon another problem I still can't solve.
If my SPM lib has another dependency, I get the above error message. I've created my own SPM package wich has another dependency and unfortunatly I can't get playground to run with: `error: no such module`.

**Comment by finestructure** [comment]
That should not be, although I've just found that some packages with dependencies seem to have issues.

For instance it works for me for these two packages with sub-dependencies:

- https://github.com/finestructure/Rester
- https://github.com/JohnSundell/Publish

and they are not small. I do however also see failures (for instance https://github.com/finestructure/ValueCodable), especially when they are building C sources.

Is your package on GitHub so that I could give it a try?

**Comment by finestructure** [comment]
Actually, I take that back, https://github.com/finestructure/ValueCodable works fine 🤷‍♂️😀

**Comment by pjamroz** [comment]
I prepared a small example. Just use [https://github.com/pjamroz/ArenaTest.git](https://github.com/pjamroz/ArenaTest.git)
I get `error: no such module` with this sample package.

**Comment by finestructure** [comment]
Mmmm, that works for me. I ran

```
arena https://github.com/pjamroz/ArenaTest.git@revision:1221f00fde9ba09a645ad0cbbd02470c2b5d4e8d
```

(using `@revision:` because there are no tags)

I can then build the playground and add some sample code from the RxSwift docs:

<img width="1329" alt="Screenshot 2020-03-02 at 08 55 20" src="https://user-images.githubusercontent.com/65520/75656202-be278480-5c63-11ea-94b4-09b6650efb5a.png">

This is using Xcode 11.3.1 (11C505) on macOS 10.15 Catalina.

**Comment by pjamroz** [comment]
I've checked again - you're absolutely right. It works fine. I belive my problem might have been building for some iOS device instead MyMac.
Anyways thanks for help, and thanks for Arena - really useful little tool.

**Comment by finestructure** [comment]
Ah, great to hear it's working for you now! Thanks for reporting back and glad you find Arena useful :)
