### ISSUE TITLE
Adding library to an existing arena project

### ISSUE THREAD

**Issue by elfenlaid** [finestructure/Arena#31]
Hi there, thanks for awesome work :)

Often I'm jumping into Arena with SnapKit or something and after tinkering for a while comes the need for additional dependency. 

What I'm doing now is recreating a new project and moving whole playground sources there.

I'm a bit lost, maybe there is designated way to add libraries to the existing arena project 🤔

**Comment by finestructure** [comment]
Hey, glad you're finding Arena useful :)

What you're doing is actually currently the only way to add a dependency and it's an interesting use case that hadn't occurred to me yet!

It might be a bit tricky to weave that in but it certainly should be possible in principle.

Thanks for reporting that!

**Comment by finestructure** [comment]
This is now easily possible with Arena's new project format (1.0.0-b1, requires Xcode 12). The project now bundles up dependencies in an umbrella package `Dependencies`. Its `Package.swift` file can be edited to add additional dependencies:

![](https://user-images.githubusercontent.com/65520/96688431-759f1180-1381-11eb-8fea-57ae405d50a6.png)

![](https://user-images.githubusercontent.com/65520/96688642-b1d27200-1381-11eb-8c7e-dffe460a0b74.png)

I'm tempted to leave it at that and not try and extend Arena to modify projects in place. I don't think it'll add all that much in terms of UX.

Please chime in if you or anyone thinks otherwise!

**Comment by elfenlaid** [comment]
> This is now easily possible with Arena's new project format (1.0.0-b1, requires Xcode 12).

That's awesome 🎊🎉

**Comment by finestructure** [comment]
Here's a brief video:

https://vimeo.com/470514453
